import { notFound } from "next/navigation";
import { Markdown } from "../../../../../components/markdown";
import { Footer, Header } from "../../../../../components/site";
import { JsonLd } from "../../../../../components/json-ld";
import { getPost, getPosts, siteUrl } from "../../../../../lib/posts";
import styles from "./follow.module.css";
function humanDate(date) { return new Intl.DateTimeFormat("en-US", { dateStyle: "full", timeZone: "UTC" }).format(new Date(`${date}T00:00:00Z`)); }
export function generateStaticParams() { return getPosts().map((post) => { const [, year, month, day, slug] = post.path.split("/"); return { year, month, day, slug }; }); }
export async function generateMetadata({ params }) { const post = getPost(await params); if (!post) return {}; const image = post.image || "/assets/img/header.jpg"; return { title: post.title, description: post.description, alternates: { canonical: post.path }, openGraph: { type: "article", url: post.path, title: post.title, description: post.description, images: [image], publishedTime: post.date, authors: [post.author] }, twitter: { card: "summary_large_image", title: post.title, description: post.description, images: [image] } }; }
export default async function Post({ params }) { const post = getPost(await params); if (!post) notFound(); const shareUrl = `${siteUrl}${post.path}`; const image = post.image?.startsWith("http") ? post.image : `${siteUrl}${post.image || "/assets/img/header.jpg"}`; const schema = { "@context": "https://schema.org", "@type": "BlogPosting", headline: post.title, description: post.description, image, datePublished: post.date, author: { "@type": "Person", name: post.author }, publisher: { "@type": "Person", name: "Truong Phan", url: siteUrl }, mainEntityOfPage: { "@type": "WebPage", "@id": shareUrl } }; return <><Header /><main className="page article"><h1>{post.title}</h1><p className="byline">📅 {humanDate(post.date)} · ✍️ {post.author} · <a href={`https://twitter.com/intent/tweet?text=${encodeURIComponent(post.title)}&url=${encodeURIComponent(shareUrl)}`}>Share</a></p>{post.image && <img className="cover" src={post.image} alt={post.title} />}<nav className={styles.follow} aria-label="Follow Truong Phan"><span>Find me online</span><a href="https://twitter.com/infantiablue">X <b aria-hidden="true">↗</b></a><a href="https://github.com/infantiablue">GitHub <b aria-hidden="true">↗</b></a></nav><article className="markdown"><Markdown>{post.content}</Markdown></article></main><JsonLd data={schema} /><Footer /></>; }
