import { notFound } from "next/navigation";
import Link from "next/link";
import Image from "next/image";
import { Markdown } from "../../../../../components/markdown";
import { Footer, Header } from "../../../../../components/site";
import { JsonLd } from "../../../../../components/json-ld";
import { getPost, getPosts, siteUrl } from "../../../../../lib/posts";
import { coverSize } from "../../../../../lib/media-rules";
import styles from "./follow.module.css";
function humanDate(date) { return new Intl.DateTimeFormat("en-US", { dateStyle: "full", timeZone: "UTC" }).format(new Date(`${date}T00:00:00Z`)); }
export function generateStaticParams() { return getPosts().map((post) => { const [, year, month, day, slug] = post.path.split("/"); return { year, month, day, slug }; }); }
export async function generateMetadata({ params }) { const post = getPost(await params); if (!post) return {}; const image = post.image || "/assets/img/header.jpg"; return { title: post.title, description: post.description, alternates: { canonical: post.path }, openGraph: { type: "article", url: post.path, title: post.title, description: post.description, images: [image], publishedTime: post.date, authors: [post.author] }, twitter: { card: "summary_large_image", title: post.title, description: post.description, images: [image] } }; }
export default async function Post({ params }) { const post = getPost(await params); if (!post) notFound(); const shareUrl = `${siteUrl}${post.path}`; const image = post.image?.startsWith("http") ? post.image : `${siteUrl}${post.image || "/assets/img/header.jpg"}`; const related = getPosts().filter((candidate) => candidate.slug !== post.slug && candidate.tags.some((tag) => post.tags.includes(tag))).slice(0, 3); const schema = { "@context": "https://schema.org", "@type": "BlogPosting", headline: post.title, description: post.description, image, datePublished: post.date, dateModified: post.updated || post.date, author: { "@id": `${siteUrl}/#person`, "@type": "Person", name: post.author, url: siteUrl }, publisher: { "@id": `${siteUrl}/#person` }, mainEntityOfPage: { "@type": "WebPage", "@id": shareUrl } }; return <><Header /><main className="page article" id="main-content"><h1>{post.title}</h1><p className="byline">📅 {humanDate(post.date)} · ✍️ {post.author} · <a href={`https://twitter.com/intent/tweet?text=${encodeURIComponent(post.title)}&url=${encodeURIComponent(shareUrl)}`}>Share</a></p>{post.image && <Image className="cover" src={post.image} alt={post.imageAlt} {...coverSize} sizes="(max-width: 1152px) 83vw, 960px" />}<nav className={styles.follow} aria-label="Follow Truong Phan"><span>Find me online</span><a href="https://twitter.com/infantiablue">X <b aria-hidden="true">↗</b></a><a href="https://github.com/infantiablue">GitHub <b aria-hidden="true">↗</b></a></nav><article className="markdown"><Markdown>{post.content}</Markdown></article>{related.length > 0 && <section className="related-posts" aria-labelledby="related-posts-title"><h2 id="related-posts-title">Related writing</h2><ul>{related.map((candidate) => <li key={candidate.path}><Link href={candidate.path}>{candidate.title}</Link></li>)}</ul></section>}</main><JsonLd data={schema} /><Footer /></>; }
